### ISSUE TITLE
请问虹软有activeKey吗

### ISSUE THREAD

**Issue by git-maven** [shenbengit/ArcFace#2]
去开发者中心没找到

**Comment by shenbengit** [comment]
![image](https://user-images.githubusercontent.com/24364422/129646642-d116bcc5-cea6-4cb4-9593-e2c900b7f540.png)
不过我这用的是增值版，可以离线激活的，算法和普通版本有点出入

**Comment by git-maven** [comment]
> ![image](https://user-images.githubusercontent.com/24364422/129646642-d116bcc5-cea6-4cb4-9593-e2c900b7f540.png)
> 不过我这用的是增值版，可以离线激活的，算法和普通版本有点出入

所以从你的截图也没看到activeKey呀，只有aapid跟sdkkey- -

**Comment by shenbengit** [comment]
我到官方看了，应该是只要增值版才有activeKey，是需要购买的。
